theme: jekyll-theme-minimal
title: South Asia - Awesome Digital History 
description: A curated list of awesome things related to South Asian digital history.
# logo: "/assets/images/just-the-docs.png"
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
